apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: ${CHANNEL}
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: ${CATALOG_SOURCE}
  sourceNamespace: openshift-marketplace

