apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: openshift-operators
spec:
  channel: gitops-${GITOPS_VERSION}
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: iib-${QUAY_USER}
  sourceNamespace: openshift-marketplace

